add timestamp function

diff --git a/docker-build b/docker-build
--- a/docker-build
+++ b/docker-build
@@ -36,12 +36,30 @@ push() {
   docker push "$repo"
 }
 
+timestamp() {
+  declare FILE=$1
+
+  if [ ! -f $FILE ]; then
+      echo "File not found!"
+      exit 1
+  fi
+
+  REV=$(git rev-list -n 1 HEAD "$FILE");
+  STAMP=$(git show --pretty=format:%ai --abbrev-commit "$REV" | head -n 1);
+  touch -d "$STAMP" $FILE;
+
+  echo "Set $FILE to $STAMP"
+}
+
 case "$1" in
   "build")
     build "$REPO"
     ;;
   "push")
     push "$REPO"
+    ;;
+  "timestamp")
+    timestamp "$2"
     ;;
   *)
     usage
